services:
  api:
    build: ../app/api
    container_name: devops-api
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: devopsdb
      DB_USER: devopsuser
      DB_PASSWORD: devopspass
    depends_on:
      - db
    restart: always

  worker:
    build: ../app/worker
    container_name: devops-worker
    environment:
      WORKER_NAME: worker-1
    depends_on:
      - api
    restart: always

  frontend:
    build: ../app/frontend
    container_name: devops-frontend
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: always

  db:
    image: postgres:15
    container_name: devops-db
    environment:
      POSTGRES_DB: devopsdb
      POSTGRES_USER: devopsuser
      POSTGRES_PASSWORD: devopspass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: