name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]

jobs:
  api-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show repo structure
        run: |
          pwd
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install API dependencies
        run: |
          cd app/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test API import
        run: |
          cd app/api
          python -c "from main import app; print('FastAPI app imported successfully')"

      - name: Build API Docker image
        run: |
          cd app/api
          docker build -t devops-api .
      - name: Build Worker Docker image
        run: |
          cd app/worker
          docker build -t devops-worker .
      - name: Build Frontend Docker image
        run: |
          cd app/frontend
          docker build -t devops-frontend .